### ISSUE TITLE
File doesn't exist

### ISSUE THREAD

**Issue by jwwalker** [objective-see/DumpBTM#1] opened 2023-01-18 21:41 UTC
When I tried running dumpBTM, it said

```
ERROR: failed to load /private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v4.btm
```

So I looked in `/private/var/db/com.apple.backgroundtaskmanagement/` and found files `BackgroundItems-v3.btm` and `BackgroundItems-v7.btm`.  I'm running Ventura 13.2.

**Comment by hazcod** [comment] 2023-01-18 22:05
Hmm, ventura 13.1, operation not permitted (because of SIP?).

```shell
% sudo su
Password:
sh-3.2# cd /private/var/db/com.apple.backgroundtaskmanagement/
sh-3.2# ls
ls: .: Operation not permitted
```

Command `sfltool dumpbtm` works tough!

**Comment by objective-see** [comment] 2023-01-19 05:08
@jwwalker, thanks for the bug report and good catch. 

I've confirmed yes, that is the case
...but good news, with just an update to use the path`BackgroundItems-v7.btm` everything else works 😅

Working on some code to make the "find/use the correct `BackgroundItems-v*` file" more robust. 

@hazcod, hrmm that's odd - is it maybe because Terminal doesn't have Full Disk Access? 🤔 As on my box with SIP enabled:

```
% csrutil status                                        
System Integrity Protection status: enabled.
% ls /private/var/db/com.apple.backgroundtaskmanagement/                      
BackgroundItems-v7.btm
```

You can enable Full Disk Access for Terminal via System Preferences.

**Comment by evild3ad** [comment] 2023-01-19 15:36
```
❯ csrutil status
System Integrity Protection status: enabled.
❯ ls /private/var/db/com.apple.backgroundtaskmanagement/
BackgroundItems-v7.btm

❯ sudo ./dumpBTM
Password:
dumpBTM v0.95
Dumps (unserializes) BackgroundItems-v4.btm
ERROR: failed to load /private/var/db/com.apple.backgroundtaskmanagement/BackgroundItems-v4.btm

Do you have Full Disk Access?
```

I have Ventura 13.1. sfltool dumpbtm works, but dumpBTM always ask for "Full Disk Access". BackgroundItems-v7 exists, BackgroundItems-v4 failed to load.

**Comment by objective-see** [comment] 2023-01-19 16:14
Now fixed in release v0.96 ☺️

The .btm file is now dynamically located so it will pick up `-v4.btm` on macOS 13, and `-v7.btm` on macOS 13.1.

Release: https://github.com/objective-see/DumpBTM/releases/tag/v0.96

Binary: https://github.com/objective-see/DumpBTM/releases/download/v0.96/dumpBTM

**Comment by evild3ad** [comment] 2023-01-19 16:28
Works! :-)

**Comment by objective-see** [comment] 2023-01-19 17:24
Closing this out, as the latest fixes/version appear to sufficiently address this!  

If you encounter any other issues, feel free to (re)open or submit a new issue.

**Closed as completed by objective-see** 2023-01-19 17:24 UTC
